### ISSUE TITLE
Not working in Unity 4.6.x

### ISSUE THREAD

**Issue by furqan-dev** [javierquevedo/bubble-shooter-unity3d#1]
When I open the scene "Bust a Move", there is nothing in the Hierarchy panel and upon clicking play, there's just empty screen.

**Comment by javierquevedo** [comment]
The latest update included support for Unity 5.X.
I haven't tested it in Unity 4, and I believe it should be very simple to make it work, but since I haven't tested it is not "supported".
I might have a look into it, but feel free to submit a request with an updated version that supports it.
I have updated the documentation (readme.md) in this regard.
Thanks for your feedback.
